services:
  - type: web
    name: pearls-aqi-fastapi
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn aqi_predictor.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.16"
      - key: PYTHONPATH
        value: src
      - key: HOPSWORKS_API_KEY
        sync: false
      - key: HOPSWORKS_PROJECT
        sync: false
      - key: HOPSWORKS_HOST
        sync: false
      - key: HOPSWORKS_CERT_FOLDER
        value: .hopsworks-certs
